#!/usr/bin/env bash
#
# Captures the *content* fingerprint of the installed `@code-sherpas/pharos-tokens`
# into a git-tracked file (`.pharos-tokens.fingerprint`). The fingerprint becomes
# the canary that TurboSnap reads via `chromaui/action`'s `externals` glob: a
# pharos-tokens release that changes any byte of its published `dist/` mutates
# the fingerprint → TurboSnap detects the change in the git tree → invalidates
# every Chromatic story for that build → the next build with the same tokens
# falls back to TurboSnap's incremental path.
#
# Why hash the whole `dist/` instead of only `dist/styles.css`:
#   pharos-tokens ships CSS variables today, but a future release could add a
#   JS module (icon registry, semantic alias resolver, etc.) consumed at import
#   time. Hashing the whole publish directory captures every artifact that
#   actually lands in `node_modules/` after `pnpm install`, including
#   `package.json` (version field) and any `.d.ts` shipped with the runtime.
#
# Determinism:
#   `find` is run from inside the package dir so the hashed paths are
#   package-relative (`./dist/...`). Output is sorted (`LC_ALL=C sort`) so two
#   machines with different locales produce the same final hash. Each file is
#   hashed individually with `sha256sum`; that line stream is then hashed once
#   more to produce a single fingerprint.
#
# Exit codes:
#   0 — fingerprint file written (or already up-to-date).
#   1 — pharos-tokens not installed (run `pnpm install` first).
#   2 — pre-flight tool missing (sha256sum, jq, find).

set -euo pipefail

FINGERPRINT_FILE=".pharos-tokens.fingerprint"
PKG_DIR="node_modules/@code-sherpas/pharos-tokens"

# Pre-flight: every tool we use must be on PATH.
for cmd in sha256sum jq find; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: \`$cmd\` is required by $0 but was not found on PATH" >&2
    exit 2
  fi
done

if [[ ! -d "$PKG_DIR" ]]; then
  echo "error: $PKG_DIR not found. Run \`pnpm install\` first." >&2
  exit 1
fi

VERSION=$(jq -r .version "$PKG_DIR/package.json")

# Hash every file under the package directory (not just dist/) — covers the
# whole installed artifact: dist/, package.json, README, etc. Paths are
# package-relative so the hash is machine-independent.
DIST_SHA=$(
  cd "$PKG_DIR"
  find . -type f -print0 \
    | LC_ALL=C sort -z \
    | xargs -0 sha256sum \
    | sha256sum \
    | cut -d' ' -f1
)

cat > "$FINGERPRINT_FILE" <<EOF
# @code-sherpas/pharos-tokens content fingerprint.
# Generated by scripts/snapshot-pharos-tokens.sh — do not edit manually.
# Re-run \`pnpm postinstall\` (or \`bash scripts/snapshot-pharos-tokens.sh\`)
# after bumping the dependency.
version=$VERSION
content_sha256=$DIST_SHA
EOF

echo "wrote $FINGERPRINT_FILE — version=$VERSION sha=${DIST_SHA:0:12}…"
